//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_News_GetAll_Result
    {
        public System.Guid NewsId { get; set; }
        public Nullable<System.Guid> NewsCategoryId { get; set; }
        public int NewsCodeNumber { get; set; }
        public string NewsAvatar { get; set; }
        public string NewsTitle { get; set; }
        public string NewsSummary { get; set; }
        public string NewsContent { get; set; }
        public Nullable<long> TotalOfLike { get; set; }
        public Nullable<long> TotalOfComment { get; set; }
        public Nullable<long> TotalOfShare { get; set; }
        public Nullable<long> TotalOfView { get; set; }
        public bool IsVip { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public bool IsDeleted { get; set; }
    }
}
