//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_Video_GetForView_PAGING_Result
    {
        public System.Guid VideoId { get; set; }
        public Nullable<System.Guid> VideoCategoryId { get; set; }
        public Nullable<System.Guid> VideoSubCategoryId { get; set; }
        public string VideoCodeNumber { get; set; }
        public string VideoName { get; set; }
        public string VideoThumbnail { get; set; }
        public Nullable<long> TotalOfViews { get; set; }
        public Nullable<System.Guid> CreatedBy { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<System.Guid> AccountId { get; set; }
        public string Username { get; set; }
        public string FullName { get; set; }
        public Nullable<long> RC { get; set; }
    }
}
