//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_VideoTag_GETALL_Result
    {
        public Nullable<System.Guid> VideoTagId { get; set; }
        public string VideoTagName { get; set; }
        public Nullable<int> TotalOfVideos { get; set; }
    }
}
