//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_RecruitmentTitle_GetAll_Result
    {
        public System.Guid RecruitmentTitleId { get; set; }
        public string Title1 { get; set; }
        public string Summary1 { get; set; }
        public string Title2 { get; set; }
        public string Summary2 { get; set; }
        public string Title3 { get; set; }
        public string Summary3 { get; set; }
    }
}
