//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_TechCategory_GetAll_Result
    {
        public System.Guid TechCategoryId { get; set; }
        public Nullable<byte> RankOfSortingOnTop { get; set; }
        public string CategoryName { get; set; }
        public string CategoryAvatar { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public int TechCodeNumber { get; set; }
    }
}
