//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_TechLink_GetAll_Result
    {
        public System.Guid TechLinkId { get; set; }
        public string TechLinkTitle { get; set; }
        public string Title1 { get; set; }
        public string Sumary1 { get; set; }
        public string Title2 { get; set; }
        public string Sumary2 { get; set; }
        public string TechLinkUrl { get; set; }
        public string TechLinkImage { get; set; }
        public Nullable<int> Number1 { get; set; }
        public Nullable<int> Number2 { get; set; }
        public Nullable<byte> Rank { get; set; }
    }
}
