//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_CourseTechnology_getAllByCourseId_Result
    {
        public System.Guid CourseTechnologyId { get; set; }
        public Nullable<byte> RankToShow { get; set; }
        public string CourseTechnologyName { get; set; }
        public Nullable<System.Guid> TrainingCategoryId { get; set; }
        public string CourseTechImage { get; set; }
        public string LinkTo { get; set; }
        public bool IsDeleted { get; set; }
    }
}
