//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_BoxBelow_getAllByCourseId_Result
    {
        public System.Guid BoxBelowId { get; set; }
        public Nullable<byte> RankToShow { get; set; }
        public Nullable<System.Guid> TrainingCategoryId { get; set; }
        public string BoxTitle { get; set; }
        public string Boxlmage { get; set; }
        public string BoxDescription { get; set; }
        public string BoxLinkTo { get; set; }
        public bool IsDeleted { get; set; }
    }
}
