//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_RecruitmentNewsLetter_GETRELATED_CATEGORY_Result
    {
        public string Title { get; set; }
        public Nullable<int> TotalOfViews { get; set; }
        public string CompanyName { get; set; }
        public System.Guid NewsLetterId { get; set; }
        public long NewsLetterCode { get; set; }
    }
}
