//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_StudentGalery_GetAll_Result
    {
        public System.Guid ImageId { get; set; }
        public string ImageName { get; set; }
        public string ImageThumbnail { get; set; }
        public string ImageLink { get; set; }
        public Nullable<int> TotalOfViews { get; set; }
        public string StudentDescription { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public Nullable<bool> FlagThumbnail { get; set; }
        public Nullable<bool> FlagLink { get; set; }
        public bool IsDeleted { get; set; }
        public string FullName { get; set; }
        public string ImageAvatar { get; set; }
    }
}
