//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_ClassSessionDetail_GetAll_Result
    {
        public System.Guid ClassSessionDetailId { get; set; }
        public Nullable<System.Guid> ClassId { get; set; }
        public Nullable<System.Guid> ClassShiftId { get; set; }
        public Nullable<bool> IsActived { get; set; }
        public Nullable<System.DateTime> OnDate { get; set; }
        public Nullable<int> ClassWeekdayId { get; set; }
        public string ClassName { get; set; }
        public string ShiftName { get; set; }
        public string WeekName { get; set; }
    }
}
