//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_OpenClassPage_GetAll_Result
    {
        public string LinkButton { get; set; }
        public string MiddleTilte { get; set; }
        public string SubTilte { get; set; }
        public string TopImage { get; set; }
        public string TopImageAlt { get; set; }
        public string TopTitle { get; set; }
    }
}
