//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_RecruitmentNewsLetter_GETPOPULAR_Result
    {
        public System.Guid NewsLetterId { get; set; }
        public Nullable<System.Guid> CompanyId { get; set; }
        public long NewsLetterCode { get; set; }
        public string ImageLink { get; set; }
        public Nullable<bool> ImageServerFlag { get; set; }
        public string ImageAlt { get; set; }
        public string Title { get; set; }
        public Nullable<int> TotalOfLikes { get; set; }
        public Nullable<int> TotalOfViews { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
    }
}
