//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_SourcePage_GetAll_Result
    {
        public int SourceId { get; set; }
        public string TechSource { get; set; }
        public string LessonSource { get; set; }
        public string RecruitSource { get; set; }
    }
}
