//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_WelcomePage_getByID_Result
    {
        public System.Guid WelcomeId { get; set; }
        public string CompanyName { get; set; }
        public string HomeTextHead { get; set; }
        public string HomeTextDescription { get; set; }
        public string CompanySlogan { get; set; }
        public string CompanyLogo { get; set; }
        public string ImageShotcut { get; set; }
        public string Hotline { get; set; }
        public string Mail { get; set; }
        public string VideoLink { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    }
}
