//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_Tag_GetById_Result
    {
        public System.Guid TagId { get; set; }
        public string TagName { get; set; }
        public Nullable<byte> MenuId { get; set; }
    }
}
