//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_ClassDetail_GetByID_Result
    {
        public System.Guid ClassDetailId { get; set; }
        public Nullable<System.Guid> DetailUser { get; set; }
        public Nullable<System.Guid> ClassId { get; set; }
        public Nullable<byte> ClassRole { get; set; }
        public string Description { get; set; }
    }
}
