//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_CourseTeacher_getByID_Result
    {
        public System.Guid CourseTeacherId { get; set; }
        public System.Guid CourseId { get; set; }
        public System.Guid ExperiencerId { get; set; }
        public Nullable<byte> RankToShow { get; set; }
    }
}
