//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_LessonDetail_GETBYCODE_Result
    {
        public System.Guid LessonDetailId { get; set; }
        public Nullable<System.Guid> LessonId { get; set; }
        public long DetailCode { get; set; }
        public string DetailName { get; set; }
        public string DetailTitle { get; set; }
        public string DetailSummary { get; set; }
        public string DetailContent { get; set; }
        public Nullable<long> TotalOfLike { get; set; }
        public Nullable<long> TotalOfComment { get; set; }
        public Nullable<long> TotalOfShare { get; set; }
        public Nullable<long> TotalOfView { get; set; }
        public Nullable<byte> Rank { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public long LessonCode { get; set; }
        public string LessonName { get; set; }
        public string FullName { get; set; }
        public string Username { get; set; }
        public string ImageAvatar { get; set; }
        public long CategoryCode { get; set; }
        public string CategoryImage { get; set; }
        public string CategoryName { get; set; }
        public Nullable<bool> ImageFlag { get; set; }
        public string SeoImage { get; set; }
        public System.Guid LessonCategoryId { get; set; }
    }
}
