//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_TrainingBanner_GetToShow_Result
    {
        public System.Guid TrainingBannerId { get; set; }
        public byte RankToShow { get; set; }
        public string BannerlmageBackground { get; set; }
        public string BannerSlogan { get; set; }
        public string BannerTitle { get; set; }
        public string BannerSumary { get; set; }
        public string BannerLinkTo { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public bool IsDeleted { get; set; }
    }
}
