//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCF.DataAccessLayer.Models
{
    using System;
    
    public partial class WEB_IMIC_SP_RecruitmentNewsLetter_GETBYCODE_Result
    {
        public System.Guid NewsLetterId { get; set; }
        public System.Guid CompanyId { get; set; }
        public long NewsLetterCode { get; set; }
        public string ImageLink { get; set; }
        public Nullable<bool> ImageServerFlag { get; set; }
        public string ImageAlt { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Content { get; set; }
        public Nullable<int> TotalOfShareFacebook { get; set; }
        public Nullable<int> TotalOfShareGoogle { get; set; }
        public Nullable<int> TotalOfShareTwitter { get; set; }
        public Nullable<int> TotalOfShareIn { get; set; }
        public Nullable<int> TotalOfLikes { get; set; }
        public Nullable<int> TotalOfViews { get; set; }
        public Nullable<byte> Rank { get; set; }
        public Nullable<System.Guid> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedTime { get; set; }
        public Nullable<System.Guid> ApprovedBy { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public string ContactInfo { get; set; }
        public string EmployerInfo { get; set; }
        public string CompanyName { get; set; }
        public string CompanyFullName { get; set; }
    }
}
